# Generated by Django 5.0.3 on 2024-03-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='painting',
            name='autor',
        ),
        migrations.AddField(
            model_name='painting',
            name='autor',
            field=models.ManyToManyField(to='paintings.author'),
        ),
    ]
