# Generated by Django 5.0.3 on 2024-03-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0002_remove_painting_autor_painting_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='brth_date',
            field=models.DateField(blank=True, null=True, verbose_name='birth date'),
        ),
        migrations.AlterField(
            model_name='author',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='painting',
            name='autor',
            field=models.ManyToManyField(blank=True, null=True, to='paintings.author'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='creation_date',
            field=models.DateField(blank=True, null=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
