# Generated by Django 5.0.3 on 2024-03-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0003_painting_status_alter_author_brth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='autor',
            field=models.ManyToManyField(to='paintings.author'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='pub_date',
            field=models.DateTimeField(blank=True, verbose_name='date published'),
        ),
    ]
