# Generated by Django 5.0.3 on 2024-03-16 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0004_alter_painting_autor_alter_painting_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='autor',
            field=models.ManyToManyField(blank=True, to='paintings.author'),
        ),
    ]
